### ISSUE TITLE
calcurse-caldav not working, python 3.7

### ISSUE THREAD

**Issue by trev-dev** [lfos/calcurse#138]
I can't seem to get calcurse-caldav working. Using Arch Linux with Python 3.7. Not sure where I done goof'd.

config: 
```
# If you want to synchronize calcurse with a CalDAV server using
# calcurse-caldav, create a new directory ~/.calcurse/caldav/, copy this file
# to ~/.calcurse/caldav/config and adjust the configuration below.

[General]
# Path to the calcurse binary that is used for importing/exporting items.
Binary = calcurse

# Host name of the server that hosts CalDAV.
Hostname = https://cloud.example.ca

# Path to the CalDAV calendar on the host specified above.
Path = /remote.php/dav/calendars/username/calendar/

# Type of authentication to use. Must be "basic" or "oauth2"
AuthMethod = basic

# Enable this if you want to skip SSL certificate checks.
InsecureSSL = No

# This option allows you to filter the types of tasks synced. To this end, the
# value of this option should be a comma-separated list of item types, where
# each item type is either "event", "apt", "recur-event", "recur-apt", "todo",
# "recur" or "cal". Note that the comma-separated list must not contain any
# spaces. Refer to the documentation of the --filter-type command line argument
# of calcurse for more details. Set this option to "cal" if the configured
# CalDAV server doesn't support tasks, such as is the case with Google
# Calendar.
SyncFilter = cal,todo

# Disable this option to actually enable synchronization. If it is enabled,
# nothing is actually written to the server or to the local data files. If you
# combine DryRun = Yes with Verbose = Yes, you get a log of what would have
# happened with this option disabled.
DryRun = Yes

# Enable this if you want detailed logs written to stdout.
Verbose = Yes

# Credentials for HTTP Basic Authentication. Leave this commented out if you do
# not want to use authentication.
#[Auth]
Username = username
Password = password

# Optionally specify additional HTTP headers here.
#[CustomHeaders]
#User-Agent = Mac_OS_X/10.9.2 (13C64) CalendarAgent/176

# Use the following to synchronize with an OAuth2-based service
# such as Google Calendar.
#[OAuth2]
#ClientID = your_client_id
#ClientSecret = your_client_secret

# Scope of access for API calls. Synchronization requires read/write.
#Scope = https://example.com/resource/scope

# Change the redirect URI if you receive errors, but ensure that it is identical
# to the redirect URI you specified in the API settings.
RedirectURI = http://127.0.0.1
```

Output of `calcurse-caldav --init=keep-remote`

```
/usr/bin/calcurse-caldav:501: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(open(configfn))
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Connecting to https://cloud.trevdev.ca...
Removing all local calcurse objects...
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/httplib2/__init__.py", line 1187, in _conn_request
    conn.connect()
  File "/usr/lib/python3.7/site-packages/httplib2/__init__.py", line 999, in connect
    address_info = socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM)
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 629, in <module>
    etagdict = get_etags(conn)
  File "/usr/bin/calcurse-caldav", line 220, in get_etags
    headers, body = remote_query(conn, "REPORT", absolute_uri, headers, body)
  File "/usr/bin/calcurse-caldav", line 182, in remote_query
    resp, body = conn.request(path, cmd, body=body, headers=headers)
  File "/usr/lib/python3.7/site-packages/httplib2/__init__.py", line 1514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python3.7/site-packages/httplib2/__init__.py", line 1264, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3.7/site-packages/httplib2/__init__.py", line 1194, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at https

```

**Comment by lfos** [comment]
Remove the `https://` prefix from the host name.

**Comment by trev-dev** [comment]
Aha, thanks so much @lfos !
