### ISSUE TITLE
Sync with mailbox.org - SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by klynxz** [lfos/calcurse#146]
[General]
Binary = calcurse

Hostname = dav.mailbox.org
Path = /caldav/50

InsecureSSL = No
SyncFilter = cal,todo
DryRun = Yes
Verbose = Yes

[Auth]
Username = me@mailbox.org
Password = mypass

`calcurse 4.3.0`

`calcurse-caldav --init=two-way`

```
/usr/bin/calcurse-caldav:501: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(open(configfn))
Connecting to dav.mailbox.org...
Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 629, in <module>
    etagdict = get_etags(conn)
  File "/usr/bin/calcurse-caldav", line 220, in get_etags
    headers, body = remote_query(conn, "REPORT", absolute_uri, headers, body)
  File "/usr/bin/calcurse-caldav", line 182, in remote_query
    resp, body = conn.request(path, cmd, body=body, headers=headers)
  File "/home/sasaki/.local/lib/python3.7/site-packages/httplib2/__init__.py", line 1514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/sasaki/.local/lib/python3.7/site-packages/httplib2/__init__.py", line 1264, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/sasaki/.local/lib/python3.7/site-packages/httplib2/__init__.py", line 1187, in _conn_request
    conn.connect()
  File "/home/sasaki/.local/lib/python3.7/site-packages/httplib2/__init__.py", line 1013, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)

```

`calcurse-caldav --init=two-way --debug`
```

/usr/bin/calcurse-caldav:501: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(open(configfn))
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Connecting to dav.mailbox.org...
> REPORT https://dav.mailbox.org/caldav/50/
> Headers: {'Authorization': 'Basic ZmVsaXBlQmR1aklaUUYyeXVfYnJMU==', 'Content-Type': 'application/xml; charset=utf-8', 'Depth': '1'}
> <?xml version="1.0" encoding="utf-8" ?><C:calendar-query xmlns:D="DAV:"                   xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag /></D:prop><C:filter><C:comp-filter name="VCALENDAR" /></C:filter></C:calendar-query>

Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 629, in <module>
    etagdict = get_etags(conn)
  File "/usr/bin/calcurse-caldav", line 220, in get_etags
    headers, body = remote_query(conn, "REPORT", absolute_uri, headers, body)
  File "/usr/bin/calcurse-caldav", line 182, in remote_query
    resp, body = conn.request(path, cmd, body=body, headers=headers)
  File "/home/sasaki/.local/lib/python3.7/site-packages/httplib2/__init__.py", line 1514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/sasaki/.local/lib/python3.7/site-packages/httplib2/__init__.py", line 1264, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/sasaki/.local/lib/python3.7/site-packages/httplib2/__init__.py", line 1187, in _conn_request
    conn.connect()
  File "/home/sasaki/.local/lib/python3.7/site-packages/httplib2/__init__.py", line 1013, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)

```

note: Im on Arch Linux

is there something I'm missing?

**Comment by lfos** [comment]
Seems like their certificate is not trusted (self-signed). You can enable `InsecureSSL` if you want to sync anyways.

**Comment by lfos** [comment]
Closing. Please reopen if you feel there is anything we should fix.
