### ISSUE TITLE
error trying to start calcurse-caldav

### ISSUE THREAD

**Issue by holalluis** [lfos/calcurse#160]
```
/usr/local/bin/calcurse-caldav:564: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(open(configfn))
Connecting to apidata.googleusercontent.com...
Traceback (most recent call last):
  File "/usr/local/bin/calcurse-caldav", line 689, in <module>
    cred = run_auth(authcode)
  File "/usr/local/bin/calcurse-caldav", line 192, in run_auth
    storage = Storage(oauth_file)
NameError: name 'Storage' is not defined
```

**Comment by lfos** [comment]
You need to install the oauth2client Python library if you want to use OAuth2 authentication.

**Comment by holalluis** [comment]
the command ''' python3 -m pip install oauth2client ''' solved the problem. It would be good mentioning that in the error so people that finds the same error could install it also.

thanks
