### ISSUE TITLE
calcurse-caldav error on init

### ISSUE THREAD

**Issue by jayghoshter** [lfos/calcurse#276]
calcurse version 4.6.0

I get this error when trying to use calcurse-caldav: 

`calcurse-caldav --init=keep-remote`

```
Running command: ['calcurse', '--version']
Connecting to ---REDACTED---
Removing all local calcurse objects...
Running command: ['calcurse', '-F', '--filter-hash=XXX']
> REPORT http://---REDACTED---
> Headers: {'Content-Type': 'application/xml; charset=utf-8', 'Depth': '1'}
> <?xml version="1.0" encoding="utf-8" ?><C:calendar-query xmlns:D="DAV:"                   xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag /></D:prop><C:filter><C:comp-filter name="VCALENDAR" /></C:filter></C:calendar-query>

Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 746, in <module>
    etagdict = get_etags(conn)
  File "/usr/bin/calcurse-caldav", line 275, in get_etags
    headers, body = remote_query(conn, "REPORT", absolute_uri, headers, body)
  File "/usr/bin/calcurse-caldav", line 236, in remote_query
    resp, body = conn.request(path, cmd, body=body, headers=headers)
  File "/usr/lib/python3.8/site-packages/httplib2/__init__.py", line 1982, in request
    (response, content) = self._request(
  File "/usr/lib/python3.8/site-packages/httplib2/__init__.py", line 1663, in _request
    for authorization in self._auth_from_challenge(
  File "/usr/lib/python3.8/site-packages/httplib2/__init__.py", line 1530, in _auth_from_challenge
    yield AUTH_SCHEME_CLASSES[scheme](
  File "/usr/lib/python3.8/site-packages/httplib2/__init__.py", line 663, in __init__
    self.A1 = "".join(
TypeError: sequence item 0: expected str instance, NoneType found

```

**Comment by pimbe** [comment]
I am also having problems, can I see your caldav config file?

**Comment by jayghoshter** [comment]
Here's my config file. 
```
# If you want to synchronize calcurse with a CalDAV server using
# calcurse-caldav, create a new directory ~/.calcurse/caldav/, copy this file
# to ~/.calcurse/caldav/config and adjust the configuration below.

[General]
# Path to the calcurse binary that is used for importing/exporting items.
Binary = calcurse

# Host name of the server that hosts CalDAV.
Hostname = <hostname>

# Path to the CalDAV calendar on the host specified above.
Path = /path/to/ics

# Type of authentication to use. Must be "basic" or "oauth2"
#AuthMethod = basic

# Enable this if you want to skip SSL certificate checks.
InsecureSSL = No

# Disable this if you want to use HTTP instead of HTTPS.
# Using plain HTTP is highly discouraged.
HTTPS = No

# This option allows you to filter the types of tasks synced. To this end, the
# value of this option should be a comma-separated list of item types, where
# each item type is either "event", "apt", "recur-event", "recur-apt", "todo",
# "recur" or "cal". Note that the comma-separated list must not contain any
# spaces. Refer to the documentation of the --filter-type command line argument
# of calcurse for more details. Set this option to "cal" if the configured
# CalDAV server doesn't support tasks, such as is the case with Google
# Calendar.
SyncFilter = cal

# Disable this option to actually enable synchronization. If it is enabled,
# nothing is actually written to the server or to the local data files. If you
# combine DryRun = Yes with Verbose = Yes, you get a log of what would have
# happened with this option disabled.
DryRun = No

# Enable this if you want detailed logs written to stdout.
Verbose = Yes

# Credentials for HTTP Basic Authentication. Leave this commented out if you do
# not want to use authentication.
#[Auth]
#Username = user
#Password = pass

# Optionally specify additional HTTP headers here.
#[CustomHeaders]
# User-Agent = Mac_OS_X/10.9.2 (13C64) CalendarAgent/176

# Use the following to synchronize with an OAuth2-based service
# such as Google Calendar.
#[OAuth2]
#ClientID = your_client_id
#ClientSecret = your_client_secret

# Scope of access for API calls. Synchronization requires read/write.
# Scope = 

# Change the redirect URI if you receive errors, but ensure that it is identical
# to the redirect URI you specified in the API settings.
#RedirectURI = http://127.0.0.1

```
