### ISSUE TITLE
SSL Wrong Version Number

### ISSUE THREAD

**Issue by poxin13** [lfos/calcurse#297]
Attempting to setup caldav with a local davmail server

```
➜  ~ calcurse-caldav --init=keep-local 
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Connecting to localhost:1080...
Removing all objects from the CalDAV server...
Traceback (most recent call last):
  File "/bin/calcurse-caldav", line 726, in <module>
    etagdict = get_etags(conn)
  File "/bin/calcurse-caldav", line 275, in get_etags
    headers, body = remote_query(conn, "REPORT", absolute_uri, headers, body)
  File "/bin/calcurse-caldav", line 236, in remote_query
    resp, body = conn.request(path, cmd, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1948, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1621, in _request
    (response, content) = self._conn_request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1528, in _conn_request
    conn.connect()
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1311, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)
```

```
[General]
Binary = calcurse
Hostname = localhost:1080
Path = /owa/calendar/
AuthMethod = basic
InsecureSSL = Yes
HTTPS = Yes
```

**Comment by poxin13** [comment]
Sovled, my issue with davmail config correct path was `http://localhost:1080/users/mail@company.com/calendar`
