### ISSUE TITLE
[calcurse-caldav] REPORT and GET and ending `/`

### ISSUE THREAD

**Issue by atticus-sullivan** [lfos/calcurse#318]
**Version information.** 
```
$ calcurse -v
calcurse 4.6.0 -- text-based organizer
```

**Bug description.**
I have an url to a caldav where the server returns `501` to the REPORT request of `calcurse-caldav`. So I tried and in the webbrowser I'm indeed able to download the `iCal` file. Therefore, I changed the request type of `calcurse-caldav` from `REPORT` to `GET` (I'm not into this so correct me if this implies any problems) and I got one step further, from
```
$ calcurse-caldav --init=keep-remote -v --debug
Loading configuration from ~/.config/calcurse/caldav/config...
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Running command: ['calcurse', '--version']
Connecting to <domain>...
Removing all local calcurse objects...
> REPORT **<URL>**
> Headers: {'Content-Type': 'application/xml; charset=utf-8', 'Depth': '1'}
> <?xml version="1.0" encoding="utf-8" ?><C:calendar-query xmlns:D="DAV:"                   xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag /></D:prop><C:filter><C:comp-filter name="VCALENDAR" /></C:filter></C:calendar-query>

< Status: 501 ()
< Headers: {'date': 'Thu, 17 Sep 2020 17:33:16 GMT', 'server': 'Apache TomEE', 'strict-transport-security': 'max-age=31536000; includeSubDomains;', 'x-frame-options': 'sameorigin', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-type': 'text/html;charset=utf-8', 'content-language': 'en', 'content-length': '1112', 'vary': 'User-Agent', 'connection': 'close', 'status': '501'}
< <!doctype html><html lang="en"><head><title>HTTP Status 501 – Not Implemented</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 501 – Not Implemented</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Method [REPORT] is not implemented by this servlet for this URI</p><p><b>Description</b> The server does not support the functionality required to fulfill the request.</p><hr class="line" /><h3>Apache Tomcat (TomEE)/8.5.41 (7.1.1)</h3></body></html>

error: The server at campus.tum.de replied with HTTP status code 501 () while
error: trying to access **<my URL>**
```

to
```
$ calcurse-caldav --init=keep-remote -v --debug
Loading configuration from ~/.config/calcurse/caldav/config...
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Running command: ['calcurse', '--version']
Connecting to **<domain>.**..
Removing all local calcurse objects...
> GET **<URL>**
> Headers: {'Content-Type': 'application/xml; charset=utf-8', 'Depth': '1'}
> <?xml version="1.0" encoding="utf-8" ?><C:calendar-query xmlns:D="DAV:"                   xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag /></D:prop><C:filter><C:comp-filter name="VCALENDAR" /></C:filter></C:calendar-query>

< Status: 500 ()
< Headers: {'date': 'Thu, 17 Sep 2020 17:35:11 GMT', 'server': 'Apache TomEE', 'strict-transport-security': 'max-age=31536000; includeSubDomains;', 'x-frame-options': 'sameorigin', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-type': 'text/plain;charset=UTF-8', 'content-language': 'de', 'content-length': '21', 'vary': 'User-Agent', 'connection': 'close', 'status': '500'}
< Ungültige Parameter.

error: The server at campus.tum.de replied with HTTP status code 500 () while
error: trying to access **<URL>**
```

Since I got the `< Ungültige Parameter.` in the Browser too at first, I knew the problem is the ending `/`. 
So I changed
```
path = '/' + config.get('General', 'Path').strip('/')
```
to
```
path = '/' + config.get('General', 'Path').strip('/') + '/'
```
(Line 689 in the sourcecode on [https://git.calcurse.org/calcurse.git/tree/contrib/caldav/calcurse-caldav.py](https://git.calcurse.org/calcurse.git/tree/contrib/caldav/calcurse-caldav.py))
But this works only partly, now I get
```
$ calcurse-caldav --init=keep-remote -v --debug
Loading configuration from ~/.config/calcurse/caldav/config...
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Running command: ['calcurse', '--version']
Connecting to **<domain>**...
Removing all local calcurse objects...
> GET **<URL>**
> Headers: {'Content-Type': 'application/xml; charset=utf-8', 'Depth': '1'}
> <?xml version="1.0" encoding="utf-8" ?><C:calendar-query xmlns:D="DAV:"                   xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag /></D:prop><C:filter><C:comp-filter name="VCALENDAR" /></C:filter></C:calendar-query>

< Status: 200 ()
< Headers: {'date': 'Thu, 17 Sep 2020 17:36:27 GMT', 'server': 'Apache TomEE', 'strict-transport-security': 'max-age=31536000; includeSubDomains;', 'x-frame-options': 'sameorigin', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-disposition': 'attachment; filename=calendar.ics', 'content-type': 'text/calendar;charset=UTF-8', 'content-language': 'de', 'vary': 'User-Agent', 'transfer-encoding': 'chunked', 'status': '200', 'content-location': '**<URL>**'}
< BEGIN:VCALENDAR
**<iCal Data>**
< END:VCALENDAR

Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 746, in <module>
    etagdict = get_etags(conn)
  File "/usr/bin/calcurse-caldav", line 278, in get_etags
    root = etree.fromstring(body)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```

Can someone help me to get this working (sorry for the inconvenience that this won't really be reproducable by someone else, but since the CalDav isn't proteceted, I can't even share the URL here)?

PS: And sorry for maybe mixing up multiple issues.

**Comment by lfos** [comment]
Thanks for the report. What exactly do you mean by "the CalDav isn't proteceted"? Is there some other form of authentication happening in the browser? Did you try to reproduce the browser download via curl(1)?

**Comment by atticus-sullivan** [comment]
Already downloaded with curl, no trouble there. By protected I mean that there is no authentication going on there, therefore I don't want to post the link here.

**Comment by lfos** [comment]
Could you clarify on what you mean by "able to download the iCal file"? Did you confirm that the server you're trying to set up does support CalDav (and is not just offering a single downloadable iCal file)?

**Comment by atticus-sullivan** [comment]
Hm, I'm not quite sure, there might be just a downloadable iCal  file (they call it something like "iCal Calendar").

Then it might be that there isn't even a CalDav Server on the other side. Just being curious, are there any plans to support automatic iCal import for cases like this?

**Comment by lfos** [comment]
You can download the iCal file with an external tool (e.g. curl) and then use `calcurse --import` to import it.

**Comment by atticus-sullivan** [comment]
This is possible, but is there a way to avoid that appointments are imported multiple times? (or is this capability yet to create?)

**Comment by lfos** [comment]
There's PR #270; it includes an incomplete implementation and a workaround in the form of a pre-load hook that drops duplicate items.
