### ISSUE TITLE
ssl error with calcurse-caldav

### ISSUE THREAD

**Issue by pasau** [lfos/calcurse#82]
i get this error when running calcurse-caldav --init=two-ways

`ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:777)`

i checked that my server and my client have the same openssl version:
on client:
`openssl version`
`OpenSSL 1.1.0g  2 Nov 2017`

on server:
`openssl version`
`OpenSSL 1.1.0g-fips  2 Nov 2017`

the calendar server is accessible with different clients, and worked in the past with calcurse-caldav.

Here is the full trace from calcurse-caldav --init=two-ways:
`Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 629, in <module>
    etagdict = get_etags(conn)
  File "/usr/bin/calcurse-caldav", line 220, in get_etags
    headers, body = remote_query(conn, "REPORT", absolute_uri, headers, body)
  File "/usr/bin/calcurse-caldav", line 182, in remote_query
    resp, body = conn.request(path, cmd, body=body, headers=headers)
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1321, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1071, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 994, in _conn_request
    conn.connect()
  File "/usr/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:777)`

And the config file:

`[General]`
`Binary = calcurse`
`Hostname = xxx.xxx.xxx.xxx:5232`
`Path = /path/tocalendar/`
`AuthMethod = basic`
`InsecureSSL = Yes`
`DryRun = No`
`Verbose = Yes`
`[Auth]`
`Username = user`
`Password = password`

**Comment by lfos** [comment]
Which server are you using?

**Comment by lfos** [comment]
Closing this. Please reopen if the issue persists.
