### ISSUE TITLE
Sync caldav to Nextcloud ERROR

### ISSUE THREAD

**Issue by insanerwayner** [lfos/calcurse#95]
## Config
```
[General]
Binary = calcurse
Hostname = https://darthwayne.yourownnet.cloud:9543
Path = /remote.php/dav

AuthMethod = basic
InsecureSSL = No

SyncFilter = cal,todo

DryRun = Yes
Verbose = Yes

[Auth]
Username = Username
Password = Password
```

## Output
```
Connecting to https://darthwayne.yourownnet.cloud:9543...
Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 518, in <module>
    etagdict = get_etags(conn)
  File "/usr/bin/calcurse-caldav", line 154, in get_etags
    headers, body = remote_query(conn, "REPORT", path, {}, body)
  File "/usr/bin/calcurse-caldav", line 114, in remote_query
    conn.request(cmd, path, headers=headers, body=body)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Is it that it doesn't like the port number? if I take out ```https://```, I get this:
```
Connecting to darthwayne.yourownnet.cloud:9543...
Pushing new object 82dac662551adbb74873f618e0bfb2fc68b57785 to the server.
error: The server at darthwayne.yourownnet.cloud:9543 replied with HTTP status
error: code 403 (Forbidden) while trying to access
error: /remote.php/dav/82dac662551adbb74873f618e0bfb2fc68b57785.ics.
```

**Comment by loweryaustin** [comment]
Why are you using a port number? Nextcloud uses port 80 for it's caldav implementation. You can find the url to use in the Calendar app within nextcloud on the bottom lefthand side when you click the "Setings & Import" button. I would recommend something like `darthwayne.yourownnet.cloud` for the hostname.
Also I noticed that you have the `[Auth]` tag commented out. This will prevent you from being able to connect period. That is what caused my problem here: #96

**Comment by insanerwayner** [comment]
My Nextcloud instance is hosted and this is the port that it is implemented on, so even in my "Settings and import it is written as ```https://darthwayne.yourownnet.cloud:9543/remote.php/dav/```"

That comment on ```[Auth]``` must have been a mistype at the time, but as of right now it is not commented out.

**Comment by loweryaustin** [comment]
@insanerwayner I see. It would be interesting to see if I could setup a test server with apache and nextcloud on the same port that you've got configured and try to reproduce the issue. 
Would you be able to run calcurse-caldav with the --debug and --verbose flags to see if there is any more information that could be had about it?

**Comment by insanerwayner** [comment]
```
Loading configuration from /home/wayne/.calcurse/caldav/config...
Connecting to https://darthwayne.yourownnet.cloud:9543...
> REPORT /remote.php/dav/
> Headers: {'Authorization': 'Basic ZGFydGh3YXluZUBob3RtYWlsLmNvbTpxNUtEbG1udUQ5bGU=', 'Content-Type': 'application/xml; charset=utf-8'}
> <?xml version="1.0" encoding="utf-8" ?><C:calendar-query xmlns:D="DAV:"                   xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag /></D:prop><C:filter><C:comp-filter name="VCALENDAR" /></C:filter></C:calendar-query>

Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 518, in <module>
    etagdict = get_etags(conn)
  File "/usr/bin/calcurse-caldav", line 154, in get_etags
    headers, body = remote_query(conn, "REPORT", path, {}, body)
  File "/usr/bin/calcurse-caldav", line 114, in remote_query
    conn.request(cmd, path, headers=headers, body=body)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
```

**Comment by loweryaustin** [comment]
@insanerwayner I apologize, I forgot to mention that the output of that will provide login details. The Authorization header part contains an encoded version of your login details. Could you remove the stuff after "Basic" ? I would also recommend changing your password.

**Comment by lfos** [comment]
I think we really should strip the authorization stuff from the debug logs (maybe with an option to keep it). This has happened at least 3 or 4 times now...

**Comment by lfos** [comment]
I edited the comment and deleted the Base64-encoded password but I really recommend changing your password to (especially since everybody receiving notifications for this issue still has your authorization data in their inboxes).

**Comment by lfos** [comment]
Coming back to the original issue... That debug log looks strange. Where does this traceback come from?

**Comment by insanerwayner** [comment]
Sorry this is months back, but I've finally come back to this.

I tried this again with putting the url for the server in quotes and this time I got this:

```
Connecting to "https://darthwayne.yourownnet.cloud:9543"...
Traceback (most recent call last):
  File "/usr/lib/python3.6/http/client.py", line 885, in _get_hostport
    port = int(host[i+1:])
ValueError: invalid literal for int() with base 10: '9543"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 496, in <module>
    conn = http.client.HTTPSConnection(hostname)
  File "/usr/lib/python3.6/http/client.py", line 1367, in __init__
    source_address)
  File "/usr/lib/python3.6/http/client.py", line 849, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/usr/lib/python3.6/http/client.py", line 890, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
http.client.InvalidURL: nonnumeric port: '9543"'
```

**Comment by loweryaustin** [comment]
Key part:
`nonnumeric port: '9543"'`
Read that very closely.

**Comment by insanerwayner** [comment]
That's interesting. So is putting quotes around the value of the variable not supported in the config file?

**Comment by loweryaustin** [comment]
It doesn't look like it. I hadn't ever tried before.
